name: publish

on:
  push:
    branches:
      - dist
    paths:
      - ".github/workflows/deploy.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
